language: go
go:
- 1.7
env:
- PATH=/home/travis/gopath/bin:$PATH
script:
- go test -v
before_deploy:
- go get github.com/laher/goxc
- goxc -d . -bc="darwin,windows,linux"
deploy:
  provider: releases
  api_key:
    secure: I/aHVtMg642E2JUBqRNixvr4pVSXtjwuZbgnjTGZsvH2l3QWMrgq/XJZzUv8g862cmWEO8rDlVp/tNfmoaGcokd7xHUpu3NOB8+ChfOyPqnr3LFrgErWGz6ZteRl65q/aA5qSlikMKdqrg3B8tkwRQ1Grxa31ia0lIeAQi0G/AZaY5P3THFCnIL+xae/AHamIV+P5yeJk7EAAXS/4YdvRkXs9euq+vW+LFxZCFqVSlupdcthK4pJP8YMmDx8UvDosLH8H70qKCjf21NLSbO/Sy0qxf0sRDws3Ufpuu8VVEbHwzfwxJ+bkKgQQTuOKnXTNYzKOCTUOxBbJC65LMVLDZAPpf+uCE8Ut1sw/K5cJiI1aDmnrJrC/vHvr77YHG1sWjJcfUFLZi8QAPLsK+4bQo0zi/Bb+RZMwE/9d1PGBeSYDa9Dm3JXHJgz2DaJEasdvXUjebd7ktjDcYXGvCjnBj25NSw7fMZgI9OFE5u96epEqQr9c1ZzuFIfYk0gmaE9cCpCrUUPkD6TrKPor2eccC6M/8rC4i2sRVtK2mqamNWk3Amg0/lZfFwIBhaC3an3C727TIq4icub5ZYEGTxfE783ghN8ZB32vMufrRY3f+YTmwf+7T9JU7HqynXFYZo5EtqLFjit2igRo6XLaiuMhrcF3Z7WjZ5nsHWuf8UhwVo=
  file:
    - snapshot/mgomgo_darwin_386.zip
    - snapshot/mgomgo_darwin_amd64.zip
    - snapshot/mgomgo_windows_386.zip
    - snapshot/mgomgo_windows_amd64.zip
    - snapshot/mgomgo_linux_arm.tar.gz
    - snapshot/mgomgo_linux_386.tar.gz
    - snapshot/mgomgo_linux_amd64.tar.gz
    - snapshot/mgomgo_snapshot_armhf.deb
    - snapshot/mgomgo_snapshot_i386.deb
    - snapshot/mgomgo_snapshot_amd64.deb
  skip_cleanup: true
  on:
    repo: furushchev/mgomgo
    tags: true
